# Generated by Django 5.1.1 on 2025-11-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_reviewvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewvideo',
            name='title',
        ),
    ]
