# Generated by Django 5.2.5 on 2025-08-08 06:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20250808_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
    ]
