# Generated by Django 5.1.1 on 2025-11-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_reviewvideo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewvideo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='reviewvideo',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = appears first'),
        ),
    ]
