# Generated by Django 5.2.5 on 2025-08-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_benefits_delete_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='key_ingredient',
        ),
        migrations.CreateModel(
            name='KeyIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='ingredients/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_ingredients', to='store.product')),
            ],
        ),
    ]
