# Generated by Django 5.2.5 on 2025-09-11 11:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_key_ingredient_keyingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
