# Generated by Django 5.2.5 on 2025-10-04 06:40

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_benefits_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_image', models.ImageField(blank=True, null=True, upload_to=store.models.upload_to_about)),
                ('choose_image', models.ImageField(blank=True, null=True, upload_to=store.models.upload_to_about)),
                ('impact_image', models.ImageField(blank=True, null=True, upload_to=store.models.upload_to_about)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
    ]
