# Generated by Django 4.2.16 on 2026-06-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
