# Generated by Django 5.2.1 on 2025-05-31 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_text', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='store.product')),
            ],
        ),
    ]
