# Generated by Django 4.2.16 on 2026-07-14 06:20

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Combos', max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='This description will appear below the Combos page heading.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Combo Page Content',
                'verbose_name_plural': 'Combo Page Content',
            },
        ),
    ]
