# Generated by Django 5.2.1 on 2025-05-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productbenefit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.TextField(blank=True, help_text='Enter one highlight per line'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='ProductBenefit',
        ),
    ]
