# Generated by Django 4.2.16 on 2026-07-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_combopagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_related_product',
            field=models.BooleanField(default=False),
        ),
    ]
