# Generated by Django 4.2.16 on 2026-07-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_is_related_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_related_product',
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Choose the products that should appear in the Related Products section.', related_name='recommended_for', to='store.product'),
        ),
    ]
