# Generated by Django 4.2.16 on 2026-08-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_is_related_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='h1_title',
            field=models.CharField(blank=True, help_text='Main H1 heading displayed on the product page.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description displayed in search engine results.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_keyword',
            field=models.CharField(blank=True, help_text='Primary SEO keyword for this product.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO title displayed in Google search results.', max_length=255, null=True),
        ),
    ]
