# Generated by Django 5.2.1 on 2025-06-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_is_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='small_banners/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
