# Generated by Django 4.2.16 on 2026-08-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='h1_title',
            field=models.CharField(blank=True, help_text='Main H1 heading displayed on the category page.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description displayed in search results.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='primary_keyword',
            field=models.CharField(blank=True, help_text='Primary SEO keyword for this category.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO title displayed in Google search results.', max_length=255, null=True),
        ),
    ]
