# Generated by Django 4.2.16 on 2026-08-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('category', models.CharField(default='Journal', help_text='Example: Hair Care, Face Care, Body Care', max_length=80)),
                ('kicker', models.CharField(blank=True, help_text='Example: Hair Care Guide', max_length=120)),
                ('subtitle', models.TextField(blank=True)),
                ('read_time', models.CharField(blank=True, help_text='Example: 7 min read', max_length=40)),
                ('meta_text_1', models.CharField(blank=True, help_text='Example: Plant-based & sulfate-free formulations', max_length=180)),
                ('meta_text_2', models.CharField(blank=True, help_text='Example: Zero-plastic packaging on both formats', max_length=180)),
                ('excerpt', models.TextField(blank=True, help_text='Short description shown on the Blog listing page.')),
                ('content_html', models.TextField(help_text='Paste the article HTML here. Do not include <!DOCTYPE>, <html>, <head>, <body>, or <style>. Only paste the article content.')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=220)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
