# Generated by Django 4.2.16 on 2026-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['display_order', '-published_at', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='1 = first blog, 2 = second blog, 3 = third blog, etc.'),
        ),
    ]
