# Generated by Django 4.2.16 on 2026-09-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_h1_title_product_meta_description_and_more'),
        ('blog', '0002_alter_blogpost_options_blogpost_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Select the products related to this blog.', related_name='related_blogs', to='store.product'),
        ),
    ]
