# Generated by Django 4.2.16 on 2026-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returning_discount_used',
            field=models.BooleanField(default=False),
        ),
    ]
